### ISSUE TITLE
Slide Show Not showing when no Announcements

### ISSUE THREAD

**Issue by digioz** [digioz/digioznetportal#14]
Slide Show Not showing when no Announcements.

**Comment by sartul** [comment]
Can you detail out the steps to reproduce the issue.

**Comment by digioz** [comment]
Here are the steps to reproduce: 

1. Make sure you don't have any announcements in the system, if you do delete all announcements. 
2. Log in as an admin account, and navigate to Admin Dashboard > Content > Slide Show. 
3. Add a couple of new slide images. 
4. In the Plugin table set the value for SlideShow to true for IsEnabled. 

![image](https://user-images.githubusercontent.com/1229683/108226405-8169cd00-7102-11eb-9adc-72de5369388c.png)

5. Navigate to Home > Index of site, note that slide show is not showing. 

![image](https://user-images.githubusercontent.com/1229683/108231101-0a830300-7107-11eb-9ac6-e2d7b3820c91.png)

6. Go to Admin Dashbaord > Content > Announcements and add a test announcement. 
7. Navigate back to Home > Index, note that the Slide Show is now showing. 

![image](https://user-images.githubusercontent.com/1229683/108231314-3f8f5580-7107-11eb-8e0e-b4950aaa32e7.png)

**Comment by sartul** [comment]
Added changes for this, The condition for showing Announcements was causing this issue. Please check and let me know if anything.

**Comment by digioz** [comment]
Confirmed the changes are working. Marking this as resolved. 

![image](https://user-images.githubusercontent.com/1229683/108760070-cb8feb80-7512-11eb-9c32-c1f767e94ff7.png)
