### ISSUE TITLE
Comment Like Button Not working

### ISSUE THREAD

**Issue by digioz** [digioz/digioznetportal#15]
The comment like button is not recording any user likes.

**Comment by sartul** [comment]
Can you detail out the steps to reproduce the issue.

**Comment by digioz** [comment]
Here are the steps to reproduce: 

1. Log into the system as an admin. 
2. go to Admin Dashboard > Settings > Configuration
3. Find the setting EnableCommentsOnAllPages and set it to "true". 
4. Refresh the App Pool in IIS or IIS Express to clear the cache
5. Go to Comment page and leave a comment. 
6. Click on the Thumbs Up Like Button. 
7. Note that the Like Count does not increment. 

![image](https://user-images.githubusercontent.com/1229683/108225504-9db93a00-7101-11eb-8ca2-83c6c1332d81.png)

It doesn't always happen though. 99% of the time in increments fine, only sometimes does it not work and I haven't been able to figure out why.

**Comment by sartul** [comment]
You can assign this to me , I will work on this.

**Comment by digioz** [comment]
Assigned it to you.

**Comment by sartul** [comment]
I have added changes for Likes count refresh, Please check and let me know if any issue. The Comment View is getting closed I am not sure if that's the default behavior.

**Comment by digioz** [comment]
Looks good, marking this as done. 

The closing behavior is on purpose.
